Repository AY2425S1-CS2103T-T09-3/tp, pull requests merged in 2024-11, with the labels that each got.

#156 Change `find` command functionality
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindDoctorCommand.java
  src/main/java/seedu/address/logic/commands/FindPatientCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/FindDoctorCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: priority.Medium, severity.Low, alpha-bug

#157 Fix API links in DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium, severity.Medium, alpha-bug

#154 Adding test coverage for AddAppointment
  src/main/java/seedu/address/model/AddressBook.java
  src/test/java/seedu/address/logic/commands/AddAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddDoctorCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddAppointmentCommandParserTest.java
Labels: priority.Medium, severity.Medium, alpha-bug

#155 Fix bug regarding Optional
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
Labels: priority.High, serverity.High, alpha-bug

#159 Add date parameter to user guide
  docs/UserGuide.md
Labels: type.Task, priority.Medium, severity.Medium, alpha-bug

#161 Fix deleting persons with appts bug
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: type.Bug, priority.High, alpha-bug

#163 remove delete-patient/doctor classes
  src/main/java/seedu/address/logic/commands/DeleteDoctorCommand.java
  src/main/java/seedu/address/logic/commands/DeletePatientCommand.java
  src/main/java/seedu/address/logic/parser/DeleteDoctorCommandParser.java
  src/main/java/seedu/address/logic/parser/DeletePatientCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteDoctorCommandTest.java
  src/test/java/seedu/address/logic/commands/DeletePatientCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteDoctorCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeletePatientCommandParserTest.java
Labels: type.Task, priority.Low, alpha-bug

#160 Fix duplicate person bug
  src/main/java/seedu/address/logic/commands/AddDoctorCommand.java
  src/main/java/seedu/address/logic/commands/AddPatientCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/doctor/Doctor.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddDoctorCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteAppointmentCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/doctor/DoctorTest.java
  src/test/java/seedu/address/model/patient/PatientTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: type.Bug, severity.Medium, alpha-bug

#165 Updating command summary in UG
  docs/UserGuide.md
Labels: priority.High, severity.Medium, alpha-bug

#167 Updating Quick Start in UG
  docs/UserGuide.md
Labels: priority.High, severity.Medium, alpha-bug

#173 Updating upcoming features in the UG
  docs/UserGuide.md
Labels: priority.High, severity.Medium, alpha-bug

#171 Updating FAQ section of the UG
  docs/UserGuide.md
Labels: priority.High, severity.Medium, alpha-bug

#164 Branch fix clash
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/test/java/seedu/address/logic/commands/AddAppointmentCommandTest.java
Labels: type.Task, priority.High, serverity.High, alpha-bug

#175 Change input validation for `NAME`
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddDoctorCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddPatientCommandParserTest.java
  src/test/java/seedu/address/model/person/NameTest.java
Labels: priority.High, alpha-bug

#169 Updating command details in features section of UG
  docs/UserGuide.md
  docs/images/findJohnJaneResult.png
Labels: priority.High, severity.Medium, alpha-bug

#178 Update help
  docs/images/helpMessage.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Bug, priority.High, alpha-bug

#182 Updating screenshot for Find feature in UG
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
  docs/images/findJohnJaneResult.png
Labels: priority.High, severity.Low, alpha-bug

#184 Remove appointments from SampleDataUtil
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: alpha-bug

#186 Fixing grammar error in UG
  docs/UserGuide.md
Labels: priority.Medium, serverity.VeryLow, alpha-bug

#187 Add date parameter info to UG
  docs/UserGuide.md
Labels: type.Task, priority.Medium, severity.Low, alpha-bug

#190 Change css for PDF header
  docs/_sass/minima/_base.scss
Labels: type.Task, priority.Medium, serverity.VeryLow, alpha-bug

#273 Fix issues in DG
  docs/DeveloperGuide.md
  docs/SettingUp.md
Labels: priority.Medium, severity.Low

#274 Fix UG
  docs/UserGuide.md
Labels: priority.Medium, serverity.VeryLow

#275 Fix invalid date
  src/main/java/seedu/address/logic/parser/AddPatientCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddPatientCommandParserTest.java
Labels: priority.Medium, severity.Medium

#277 Resolve issues
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium, severity.Low

#280 Fix bug regarding storage duplicates
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
Labels: serverity.High

#289 Fix issues regarding UG
  docs/UserGuide.md
Labels: priority.High, severity.Medium

#287 Fix email validation
  src/main/java/seedu/address/model/person/Email.java
Labels: serverity.High
