Repository AY2425S1-CS2103T-T09-3/tp, pull requests merged in 2024-10, with the labels that each got.

#45 Add more user stories
  docs/DeveloperGuide.md
Labels: type.Task, priority.High, severity.Low

#61 Implement execute for ListPatientCommand and ListDoctorCommand
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ListDoctorCommand.java
  src/main/java/seedu/address/logic/commands/ListPatientCommand.java
  src/main/java/seedu/address/model/doctor/DoctorPredicate.java
  src/main/java/seedu/address/model/patient/PatientPredicate.java
  src/test/java/seedu/address/logic/commands/AddPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/ListDoctorCommandTest.java
  src/test/java/seedu/address/logic/commands/ListPatientCommandTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.High

#65 Modify Person class to contain all fields
  src/main/java/seedu/address/model/doctor/Doctor.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/person/Person.java
Labels: type.Task, priority.High

#68 Updating GUI for patient contacts
  src/main/java/seedu/address/model/patient/DateOfBirth.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PatientListCard.fxml
Labels: priority.High, severity.Medium

#69 Updating GUI for doctor contacts
  src/main/java/seedu/address/ui/DoctorCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DoctorListCard.fxml
Labels: priority.High, severity.Medium

#79 Update UML for Model
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: type.Task, priority.High

#87 Add Appointment class
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/Time.java
  src/main/java/seedu/address/model/patient/DateOfBirth.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/shared/Date.java
  src/test/java/seedu/address/model/appointment/AppointmentTest.java
  src/test/java/seedu/address/model/appointment/TimeTest.java
  src/test/java/seedu/address/model/patient/DateOfBirthTest.java
Labels: type.Task, priority.High

#89 Adding AddAppointment Command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/AddDoctorCommand.java
  src/main/java/seedu/address/logic/commands/AddPatientCommand.java
  src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddDoctorCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPatientCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High, severity.Medium

#95 Update UI to show Appointments
  src/main/java/seedu/address/ui/DoctorCard.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DoctorListCard.fxml
  src/main/resources/view/PatientListCard.fxml
Labels: type.Enhancement, priority.High

#97 Updating UML diagrams
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: priority.High, severity.Low

#86 Update user guide
  docs/UserGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: type.Task, priority.Medium

#112 Fix appointment issue in storage
  src/main/java/seedu/address/model/AddressBook.java
Labels: type.Task, priority.High, serverity.High, alpha-bug

#108 Remove add and find command from UG
  docs/UserGuide.md
Labels: type.Bug, priority.Medium, alpha-bug

#107 Improve find command
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/parser/FindDoctorCommandParser.java
  src/main/java/seedu/address/logic/parser/FindPatientCommandParser.java
  src/main/java/seedu/address/model/doctor/FindDoctorPredicate.java
  src/main/java/seedu/address/model/patient/FindPatientPredicate.java
  src/test/java/seedu/address/logic/commands/FindDoctorCommandTest.java
  src/test/java/seedu/address/logic/commands/FindPatientCommandTest.java
  src/test/java/seedu/address/logic/parser/FindDoctorCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindPatientCommandParserTest.java
Labels: type.Bug, priority.Medium, alpha-bug

#111 Remove add command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalDoctors.java
Labels: type.Bug, priority.Medium, alpha-bug

#119 Remove edit command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Bug, priority.Medium, alpha-bug

#120 Fix test for delete-appt-successfully
  src/test/java/seedu/address/logic/commands/DeleteAppointmentCommandTest.java
Labels: type.Bug, priority.Medium, alpha-bug

#116 Fix UG for find-patient/find-doctor
  docs/UserGuide.md
Labels: type.Task, priority.Medium, alpha-bug

#118 Add appointment references to DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium, severity.Low, alpha-bug

#123 Update SampleDataUtil.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Enhancement, priority.Medium, alpha-bug

#127 Add tests for manual testing
  docs/DeveloperGuide.md
Labels: type.Bug, priority.Medium, priority.Low, alpha-bug

#128 Update UI
  copyright.txt
  src/main/java/seedu/address/ui/DoctorCard.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/medical-symbol.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: priority.Medium, alpha-bug

#146 Updating UG with AddAppointment command
  docs/UserGuide.md
Labels: priority.Medium, severity.Medium, alpha-bug

#147 Update tutorial ug
  docs/UserGuide.md
  docs/images/Ui.png
Labels: priority.Medium

#148 Updating UG with DeleteAppointment command
  docs/UserGuide.md
Labels: priority.Medium, severity.Medium, alpha-bug

#150 Updating sample data for app booting up
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Medium, severity.Medium, alpha-bug
